# Generated by Django 5.0.2 on 2024-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=200)),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("primary", "primary"),
                            ("success", "success"),
                            ("neutral", "neutral"),
                            ("warning", "warning"),
                            ("danger", "danger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
