# Generated by Django 5.0.2 on 2024-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_client_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
